apiVersion: v1
kind: Service
metadata:
  name: books-service-externalip
  labels:
    service: books-service-externalip
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: http
  externalIPs:
    - 1.2.4.114
  selector:
    app: books