# do not store your secret GitHub, Gitlab etc.
apiVersion: v1
kind: Secret
metadata:
  name: books-secret
stringData:
  DB_USERNAME: "foo"
  DB_PASSWORD: "bla"
#stringData:
#  usernameString: 'user'
#  passwordString: 'password'