apiVersion: v1
kind: ConfigMap
metadata:
  name: books-configmap
  namespace: default # if namespace exists - we don't need to point to concrete namespace in the console
data:
  applicationPort: ":9090"
  applicationName: "books"
#  app.properties: |
#    applicationPort=9090
#    applicationName=books
#  config.json: |
#    {
#      "applicationPort": "9090",
#      "applicationName": "books"
#    }