# do not store your secret GitHub, Gitlab etc.
apiVersion: v1
kind: Secret
metadata:
  name: books-secret
stringData:
  postgresConnectionUrl: 'host=postgres port=5432 dbname=books user=user password=password sslmode=disable'
#stringData:
#  usernameString: 'user'
#  passwordString: 'password'