apiVersion: v1
kind: ConfigMap
metadata:
  name: books-cm
  namespace: default
data:
  applicationPort: "9090"
  applicationName: "books"
#  app.properties: |
#    applicationPort=9090
#    applicationName=books
#  config.json: |
#    {
#      "applicationPort": "9090",
#      "applicationName": "books"
#    }