apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: books
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  # about tls in Ingress - https://kubernetes.github.io/ingress-nginx/user-guide/tls/
  # to generate certificate - HOST=<needed host> KEY_FILE=<any name>.key CERT_FILE=<any name>.crt openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout ${KEY_FILE} -out ${CERT_FILE} -subj "/CN=${HOST}/O=${HOST}" -addext "subjectAltName = DNS:${HOST}"
  # to create secret - kubectl create secret tls books-local-secret-tls --key server.key --cert server.crt
  tls:
    - hosts:
        - books.local
      secretName: books-local-secret-tls
  rules:
    - host: books.local
      http:
        paths:
          - path: /api/v1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: books
                port:
                  number: 8080
          - path: /nginx-service
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80