# do not store your secret GitHub, Gitlab etc.
apiVersion: v1
kind: Secret
metadata:
  name: secret
data:
  DB_USERNAME: Zm9vCg==
  DB_PASSWORD: YmxhCg==
#stringData:
#  usernameString: 'user'
#  passwordString: 'password'