apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    db: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    db: postgres